program = declaration, {declaration};

decl = 
   varDeclaration
   | functionDeclaration
;

(* VARIABLE *)
varDeclaration = type, varDeclarationInit;
varDeclarationInit = varDeclarationId, ['=', simpleExp];
varDeclarationId = ID;

(* FUNCTION sprawdzić czy potem mozna używać bez typów *)
functionDeclaration = [type], ID, "(", parms, ")", statement;
parms = {type, ID};


type = 
   "int"
   | "float"
   | "string"
   | "bool"
   | CURRENCY_NAME
;

int = 
   [-]
   ,
   "0" 
   | "1-9",{DIGIT}
;

float =
   int, '.' , DIGIT, {DIGIT}
;

currency = 
   (
      int 
      | float
   )
   ,
   CURRENCY_NAME
;

string = "'", {CHAR} "'";

ID = LETTER;
DIGIT = "0-9";
LETTER =
   "a-z"
   | "A-Z"
;
SYMBOL = "[" | "]" | "{" | "}" | "(" | ")" | "<" | ">" | "'" | '"' | "=" | "|" | "." | "," | ";" "_";

CHAR = 
   DIGIT
   | LETTER
   | SYMBOL
;

CURRENCY_NAME = ; (*I.E. 'PLN' | 'EUR' | 'USD';*)